#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# THUMB_TA6-T1.py
# Generated by VE3 Thumb Designer - 2026-03-09 20:16
# Edit DESIGN config to customize layout and colors.
# Run: python THUMB_TA6-T1.py <code>

import sys, io, re, unicodedata, json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageFilter
import gspread
from google.oauth2.service_account import Credentials

BASE_DIR    = Path(__file__).parent
VISUAL_DIR  = Path("D:/AUTO/VISUAL")
OUTPUT_DIR  = BASE_DIR / "thumbnails"
FONTS_DIR   = BASE_DIR.parent / "fonts"
CONFIG_FILE = BASE_DIR.parent / "config" / "config.json"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ===========================================================================
# DESIGN CONFIG (generated by Thumb Designer - edit to customize)
# ===========================================================================
DESIGN = {
    "canvas": {
        "w": 1920,
        "h": 1080
    },
    "elements": [
        {
            "id": 1,
            "type": "background",
            "x": 15,
            "y": 0,
            "w": 1920,
            "h": 1080,
            "color": "#000000",
            "image_path": ""
        },
        {
            "id": 2,
            "type": "photo",
            "x": 1326,
            "y": -200,
            "w": 606,
            "h": 1080,
            "remove_bg": False
        },
        {
            "id": 3,
            "type": "text_main",
            "x": 22,
            "y": 22,
            "w": 1290,
            "h": 814,
            "sample_text": "MY FAMILY LAUGHED WHEN I WALKED INTO MY SISTER'S WEDDING ALONE, \"SHE COULDN'T EVEN FIND A DARE\" MY FATHER SCREAMED, BEFORE PUSHING ME INTO THE FOUNTAIN. THE GUESTS CLAPPED. I SMILED ",
            "sample_highlights": "PUSHING ME INTO THE FOUNTAIN.",
            "font": "UTM-AvoBold",
            "color": "#ffffff",
            "highlight_color": "#ec0505",
            "min_font": 36,
            "max_font": 200,
            "line_spacing": 10,
            "align": "center",
            "text_transform": "none",
            "stroke_width": 0,
            "stroke_color": "#000000",
            "hi_stroke_width": 0,
            "hi_stroke_color": "#000000"
        },
        {
            "id": 4,
            "type": "hook",
            "x": 0,
            "y": 855,
            "w": 1941,
            "h": 243,
            "sample_text": "THE WILL HE  JUST BURNED",
            "font": "Anton",
            "font_size": 0,
            "color": "#ffffff",
            "bg_color": "#00bf63",
            "shape": "pill",
            "stroke_width": 5,
            "stroke_color": "#000000"
        }
    ]
}
# ===========================================================================

FONTS_MAP = {
    "UTM-AvoBold":      FONTS_DIR / "00034-UTM-AvoBold.ttf",
    "Anton":            FONTS_DIR / "Anton-Regular.ttf",
    "Bebas Neue":       FONTS_DIR / "BebasNeue-Regular.ttf",
    "Inter Bold":       FONTS_DIR / "Inter-Bold.ttf",
    "League Spartan":   FONTS_DIR / "LeagueSpartan-ExtraBold.ttf",
    "Montserrat":       FONTS_DIR / "Montserrat-VariableFont_wght.ttf",
    "Nunito":           FONTS_DIR / "Nunito-VariableFont_wght.ttf",
    "Roboto Condensed": FONTS_DIR / "RobotoCondensed-BlackItalic.ttf",
    "Zuume SemiBold":   FONTS_DIR / "Zuume SemiBold.ttf",
}


# ============ GOOGLE SHEETS ============
def load_record(code, max_retries=5):
    import time
    for attempt in range(max_retries):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            cred_path = CONFIG_FILE.parent / cfg.get("CREDENTIAL_PATH", "creds.json")
            creds = Credentials.from_service_account_file(str(cred_path), scopes=[
                "https://www.googleapis.com/auth/spreadsheets.readonly",
                "https://www.googleapis.com/auth/drive.readonly",
            ])
            gc = gspread.authorize(creds)
            ws = gc.open("KA").worksheet("INPUT")
            rows = ws.get_all_values()[1:]
            for r in rows:
                if r and r[0].strip() == code:
                    return {
                        "text_thumb": r[20].strip() if len(r) > 20 else "",
                        "hook":       r[21].strip() if len(r) > 21 else "",
                        "highlights": r[22].strip() if len(r) > 22 else "",
                    }
            return {"text_thumb": "", "hook": "", "highlights": ""}
        except Exception as e:
            wait = 3 * (attempt + 1)
            print(f"[WARN] Sheets error (attempt {attempt+1}/{max_retries}): {e}")
            if attempt < max_retries - 1:
                print(f"  Retry in {wait}s...")
                time.sleep(wait)
    print(f"[ERROR] Sheets failed after {max_retries} attempts. Cannot proceed without data.")
    return None


# ============ HELPERS ============
def get_font(name, size):
    path = FONTS_MAP.get(name)
    if path and Path(path).exists():
        try:
            return ImageFont.truetype(str(path), int(size))
        except Exception:
            pass
    return ImageFont.load_default()


def hex_rgba(h, a=255):
    h = str(h).lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        return (128, 128, 128, a)
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), a)


def clean_text(text):
    if not isinstance(text, str):
        text = str(text)
    text = unicodedata.normalize("NFKC", text)
    return (text.strip()
            .replace("\u2019", "'").replace("\u2018", "'")
            .replace("\u201c", '"').replace("\u201d", '"')
            .replace("\u2013", "-").replace("\u2014", "-"))


def wrap_text(draw, text, font, max_w):
    words = text.split()
    lines, line = [], ""
    for w in words:
        t = f"{line} {w}".strip()
        if draw.textlength(t, font=font) <= max_w:
            line = t
        else:
            if line:
                lines.append(line)
            line = w
    if line:
        lines.append(line)
    return lines or [text]


def smart_wrap_2(draw, text, font, max_w):
    if draw.textlength(text, font=font) <= max_w:
        return [text]
    best = None
    for sep in [". ", "! ", "? ", ", ", "; "]:
        idx = -1
        while True:
            idx = text.find(sep, idx + 1)
            if idx < 0:
                break
            l1 = text[:idx + len(sep)].strip()
            l2 = text[idx + len(sep):].strip()
            if l1 and l2 and draw.textlength(l1, font=font) <= max_w and draw.textlength(l2, font=font) <= max_w:
                best = [l1, l2]
    if best:
        return best
    words = text.split()
    mid = len(text) // 2
    best_diff = len(text)
    best_split = None
    pos = 0
    for i, word in enumerate(words[:-1]):
        pos += len(word) + (1 if i > 0 else 0)
        diff = abs(pos - mid)
        if diff < best_diff:
            l1 = " ".join(words[:i+1])
            l2 = " ".join(words[i+1:])
            if draw.textlength(l1, font=font) <= max_w and draw.textlength(l2, font=font) <= max_w:
                best_diff = diff
                best_split = [l1, l2]
    if best_split:
        return best_split
    return wrap_text(draw, text, font, max_w)[:2]


def split_phrases(raw):
    return [p.strip() for p in str(raw).split("|") if p.strip()]


def find_highlight_spans(full_text, phrases):
    spans = []
    for ph in phrases:
        ph = ph.strip()
        if not ph:
            continue
        tokens = [re.escape(t) for t in ph.split()]
        if not tokens:
            continue
        first, last = tokens[0], tokens[-1]
        if first and first[0].isalnum():
            first = r"\b" + first
        if last and last[-1].isalnum():
            last = last + r"\b"
        mid = r"[^\w]*\s*"
        core = first if len(tokens) == 1 else mid.join([first, *tokens[1:-1], last])
        try:
            pattern = re.compile(core, re.I | re.S)
        except re.error:
            pattern = re.compile(re.escape(ph), re.I | re.S)
        for m in pattern.finditer(full_text):
            spans.append((m.start(), m.end()))
    spans.sort()
    merged = []
    for s, e in spans:
        if merged and s <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(e, merged[-1][1]))
        else:
            merged.append((s, e))
    return merged


def draw_rich_text(draw, lines, x, y, w, font, color, hi_color, spacing, align, spans,
                   stroke_w=0, stroke_c="#000000", hi_stroke_w=0, hi_stroke_c="#000000"):
    ty = y
    char_pos = 0
    for line in lines:
        lw = int(draw.textlength(line, font=font))
        if align == "center":
            lx = x + max(0, (w - lw) // 2)
        elif align == "right":
            lx = x + w - lw - 10
        else:
            lx = x + 10

        segs, cur = [], 0
        for s, e in spans:
            s2 = s - char_pos
            e2 = e - char_pos
            ls = max(s2, 0)
            le = min(e2, len(line))
            if ls >= le:
                continue
            if ls > cur:
                segs.append((line[cur:ls], False))
            segs.append((line[ls:le], True))
            cur = le
        if cur < len(line):
            segs.append((line[cur:], False))
        if not segs:
            segs = [(line, False)]

        cx = lx
        for seg, hi in segs:
            c = hex_rgba(hi_color) if hi else hex_rgba(color)
            sw = hi_stroke_w if hi else stroke_w
            sc = hex_rgba(hi_stroke_c if hi else stroke_c)
            if sw > 0:
                draw.text((cx, ty), seg, fill=c, font=font, stroke_width=sw, stroke_fill=sc)
            else:
                draw.text((cx, ty), seg, fill=c, font=font)
            cx += int(draw.textlength(seg, font=font))

        ty += font.size + spacing
        char_pos += len(line) + 1


def save_jpeg(img, path, max_bytes=2_000_000):
    rgb = img.convert("RGB")
    for _ in range(4):
        for q in range(95, 49, -5):
            buf = io.BytesIO()
            rgb.save(buf, format="JPEG", quality=q, optimize=True,
                     progressive=True, subsampling="4:2:0")
            if buf.tell() <= max_bytes:
                path.parent.mkdir(parents=True, exist_ok=True)
                with open(path, "wb") as f:
                    f.write(buf.getvalue())
                return
        new_w = int(rgb.width * 0.9)
        new_h = int(rgb.height * 0.9)
        if new_w < 640:
            break
        rgb = rgb.resize((new_w, new_h), Image.LANCZOS)
    rgb.save(path, format="JPEG", quality=50, optimize=True, progressive=True)


# ============ BACKGROUND REMOVAL ============
def remove_bg_image(img):
    """Remove background using rembg or MODNet. Returns RGBA image."""
    import io as _io
    # Try rembg (pip install rembg)
    try:
        from rembg import remove as _rembg
        buf = _io.BytesIO()
        img.save(buf, format="PNG")
        out = _rembg(buf.getvalue())
        return Image.open(_io.BytesIO(out)).convert("RGBA")
    except ImportError:
        pass
    except Exception as e:
        print(f"  [remove_bg] rembg: {e}")
    # Try MODNet (same as 4.NV_*.py)
    try:
        import sys as _sys, cv2 as _cv2, numpy as _np, torch as _torch
        from torchvision import transforms as _T
        _mdir = BASE_DIR / "MODNet"
        _src  = _mdir / "src"
        _pth  = _mdir / "modnet_photographic_portrait_matting.pth"
        if not _src.exists() or not _pth.exists():
            raise FileNotFoundError("MODNet not found")
        if str(_src) not in _sys.path:
            _sys.path.insert(0, str(_src))
        from models.modnet import MODNet as _MODNet
        _dev = _torch.device("cuda" if _torch.cuda.is_available() else "cpu")
        _m = _MODNet(backbone_pretrained=False)
        _sd = _torch.load(str(_pth), map_location=_dev)
        _sd = {k.replace("module.", ""): v for k, v in _sd.items()}
        _m.load_state_dict(_sd); _m.to(_dev).eval()
        im_rgb = img.convert("RGB")
        im_big = im_rgb.resize((im_rgb.width * 4, im_rgb.height * 4), Image.LANCZOS)
        tensor = _T.Compose([_T.ToTensor(), _T.Normalize((0.5,), (0.5,))])(
            im_big.resize((512, 512))).unsqueeze(0).to(_dev)
        with _torch.no_grad():
            _, _, matte = _m(tensor, True)
        matte_np = _cv2.resize(matte[0][0].cpu().numpy(), im_big.size, interpolation=_cv2.INTER_AREA)
        fg    = _np.array(im_big).astype(_np.uint8)
        alpha = (matte_np * 255).astype(_np.uint8)
        result = Image.fromarray(_np.dstack((fg, alpha))).filter(ImageFilter.SMOOTH_MORE)
        result = result.resize(img.size, Image.LANCZOS).convert("RGBA")
        r, g, b, a = result.split()
        a = a.filter(ImageFilter.GaussianBlur(radius=2))
        return Image.merge("RGBA", (r, g, b, a))
    except Exception as e:
        print(f"  [remove_bg] MODNet: {e}")
    return img.convert("RGBA")


# ============ RENDER ELEMENTS ============
def render_element(canvas, el, code, data):
    draw = ImageDraw.Draw(canvas)
    cw, ch = canvas.size
    t = el["type"]
    x = int(el.get("x", 0))
    y = int(el.get("y", 0))
    w = int(el.get("w", cw))
    h = int(el.get("h", ch))

    if t == "background":
        img_path = el.get("image_path", "")
        if img_path:
            full = BASE_DIR / img_path if not Path(img_path).is_absolute() else Path(img_path)
            if full.exists():
                bg = Image.open(full).convert("RGBA")
                bg = ImageOps.fit(bg, (cw, ch), Image.LANCZOS)
                canvas.paste(bg, (0, 0))
                return
        canvas.paste(Image.new("RGBA", (cw, ch), hex_rgba(el.get("color", "#1a1a2e"))), (0, 0))

    elif t == "photo":
        if el.get("remove_bg"):
            # Use nv/nv1.png when remove_bg is enabled
            photo_path = VISUAL_DIR / code / "nv" / "nv1.png"
            if not photo_path.exists():
                print(f"  [WARN] nv1.png not found: {photo_path}")
                return
            print(f"  [remove_bg] Using nv1.png, processing...")
            img = Image.open(photo_path).convert("RGBA")
            img = remove_bg_image(img)
        else:
            # Normal: try thumb_004.png, fallback to thumb_003.png, then any image
            thumb_dir = VISUAL_DIR / code / "thumbnail"
            photo_path = thumb_dir / "thumb_004.png"
            if not photo_path.exists():
                photo_path = thumb_dir / "thumb_003.png"
            if not photo_path.exists():
                for ext in (".png", ".jpg", ".jpeg", ".webp"):
                    for _f in thumb_dir.glob(f"*{ext}"):
                        photo_path = _f; break
                    else: continue
                    break
            if not photo_path.exists():
                print(f"  [WARN] Photo not found in: {thumb_dir}")
                return
            img = Image.open(photo_path).convert("RGBA")
        scale = h / img.height
        nw = int(img.width * scale)
        img = img.resize((nw, h), Image.LANCZOS)
        if nw > w:
            cx = (nw - w) // 2
            img = img.crop((cx, 0, cx + w, h))
        canvas.paste(img, (x, y), img)

    elif t == "text_main":
        text = clean_text(data.get("text_thumb", ""))
        if not text:
            return
        transform = el.get("text_transform", "none")
        if transform == "upper": text = text.upper()
        elif transform == "lower": text = text.lower()
        color       = el.get("color", "#ffffff")
        hi_color    = el.get("highlight_color", "#ffca22")
        font_name   = el.get("font", "UTM-AvoBold")
        min_sz      = int(el.get("min_font", 36))
        max_sz      = int(el.get("max_font", 200))
        spacing     = int(el.get("line_spacing", 10))
        align       = el.get("align", "center")
        stroke_w    = int(el.get("stroke_width", 0))
        stroke_c    = el.get("stroke_color", "#000000")
        hi_stroke_w = int(el.get("hi_stroke_width", 0))
        hi_stroke_c = el.get("hi_stroke_color", "#000000")
        phrases     = split_phrases(data.get("highlights", ""))

        for size in range(max_sz, min_sz - 1, -2):
            f = get_font(font_name, size)
            lines = wrap_text(draw, text, f, w - 20)
            total_h = len(lines) * size + max(0, len(lines) - 1) * spacing
            if total_h <= h - 20:
                ty = y + max(0, (h - total_h) // 2)
                full_txt = "\n".join(lines)
                spans = find_highlight_spans(full_txt, phrases)
                draw_rich_text(draw, lines, x, ty, w, f, color, hi_color, spacing, align, spans,
                               stroke_w, stroke_c, hi_stroke_w, hi_stroke_c)
                return
        f = get_font(font_name, min_sz)
        lines = wrap_text(draw, text, f, w - 20)
        full_txt = "\n".join(lines)
        spans = find_highlight_spans(full_txt, phrases)
        draw_rich_text(draw, lines, x, y + 10, w, f, color, hi_color, spacing, align, spans,
                       stroke_w, stroke_c, hi_stroke_w, hi_stroke_c)

    elif t == "hook":
        text = clean_text(data.get("hook", "")).upper()
        if not text:
            return
        color        = el.get("color", "#000000")
        bg_color     = el.get("bg_color", "#ffca22")
        font_name    = el.get("font", "Anton")
        shape        = el.get("shape", "pill")
        stroke_w     = int(el.get("stroke_width", 0))
        stroke_color = el.get("stroke_color", "#000000")
        fixed_size   = int(el.get("font_size", 0))

        bg_rgba = hex_rgba(bg_color)
        if shape == "pill" and hasattr(draw, "rounded_rectangle"):
            r = min(h // 2, 40)
            draw.rounded_rectangle([x, y, x+w, y+h], radius=r, fill=bg_rgba)
        elif shape == "rect":
            draw.rectangle([x, y, x+w, y+h], fill=bg_rgba)

        cx = x + w // 2
        if fixed_size > 0:
            f = get_font(font_name, fixed_size)
            tw = int(draw.textlength(text, font=f))
            if tw > w - 40:
                lines = smart_wrap_2(draw, text, f, w - 40)
                gap = max(4, fixed_size // 8)
                total_h = len(lines) * fixed_size + (len(lines) - 1) * gap
                start_cy = y + h // 2 - total_h // 2 + fixed_size // 2
                for i, line in enumerate(lines):
                    cy_line = start_cy + i * (fixed_size + gap)
                    if stroke_w > 0:
                        draw.text((cx, cy_line), line, fill=hex_rgba(stroke_color),
                                  font=f, anchor="mm", stroke_width=stroke_w,
                                  stroke_fill=hex_rgba(stroke_color))
                    draw.text((cx, cy_line), line, fill=hex_rgba(color), font=f, anchor="mm")
            else:
                cy = y + h // 2
                if stroke_w > 0:
                    draw.text((cx, cy), text, fill=hex_rgba(stroke_color),
                              font=f, anchor="mm", stroke_width=stroke_w,
                              stroke_fill=hex_rgba(stroke_color))
                draw.text((cx, cy), text, fill=hex_rgba(color), font=f, anchor="mm")
        else:
            # Auto-fit: largest size that fits max 2 lines
            for sz in range(h, 20, -2):
                f = get_font(font_name, sz)
                tw = int(draw.textlength(text, font=f))
                if tw <= w - 40:
                    if sz > h - 10:
                        continue
                    cy = y + h // 2
                    if stroke_w > 0:
                        draw.text((cx, cy), text, fill=hex_rgba(stroke_color),
                                  font=f, anchor="mm", stroke_width=stroke_w,
                                  stroke_fill=hex_rgba(stroke_color))
                    draw.text((cx, cy), text, fill=hex_rgba(color), font=f, anchor="mm")
                    break
                else:
                    lines = smart_wrap_2(draw, text, f, w - 40)
                    if len(lines) <= 2:
                        gap = max(4, sz // 8)
                        total_h = len(lines) * sz + (len(lines) - 1) * gap
                        if total_h <= h - 10:
                            start_cy = y + h // 2 - total_h // 2 + sz // 2
                            for i, line in enumerate(lines):
                                cy_line = start_cy + i * (sz + gap)
                                if stroke_w > 0:
                                    draw.text((cx, cy_line), line, fill=hex_rgba(stroke_color),
                                              font=f, anchor="mm", stroke_width=stroke_w,
                                              stroke_fill=hex_rgba(stroke_color))
                                draw.text((cx, cy_line), line, fill=hex_rgba(color), font=f, anchor="mm")
                            break

    elif t == "text_box":
        text = el.get("sample_text", "")
        if not text:
            return
        color      = el.get("color", "#ffffff")
        bg_color   = el.get("bg_color", "#333333")
        font_name  = el.get("font", "UTM-AvoBold")
        size       = int(el.get("font_size", 48))
        align      = el.get("align", "center")
        radius     = int(el.get("border_radius", 10))

        bg_rgba = hex_rgba(bg_color)
        if radius > 0 and hasattr(draw, "rounded_rectangle"):
            draw.rounded_rectangle([x, y, x+w, y+h], radius=radius, fill=bg_rgba)
        else:
            draw.rectangle([x, y, x+w, y+h], fill=bg_rgba)

        f = get_font(font_name, size)
        lines = wrap_text(draw, text, f, w - 20)
        total_h = len(lines) * size + max(0, len(lines) - 1) * 6
        ty = y + max(0, (h - total_h) // 2)
        for line in lines:
            lw = int(draw.textlength(line, font=f))
            if align == "center":
                lx = x + max(0, (w - lw) // 2)
            elif align == "right":
                lx = x + w - lw - 10
            else:
                lx = x + 10
            draw.text((lx, ty), line, fill=hex_rgba(color), font=f)
            ty += size + 6

    elif t == "text_static":
        text = el.get("text", "")
        if not text:
            return
        color     = el.get("color", "#ffffff")
        font_name = el.get("font", "UTM-AvoBold")
        size      = int(el.get("font_size", 60))
        align     = el.get("align", "center")
        f = get_font(font_name, size)
        tw = int(draw.textlength(text, font=f))
        if align == "center":
            tx = x + max(0, (w - tw) // 2)
        elif align == "right":
            tx = x + w - tw - 10
        else:
            tx = x + 10
        ty3 = y + max(0, (h - size) // 2)
        draw.text((tx, ty3), text, fill=hex_rgba(color), font=f)


# ============ MAIN ============
def main():
    code = sys.argv[1] if len(sys.argv) > 1 else None
    if not code:
        print("Usage: python THUMB_TA6-T1.py <code>")
        sys.exit(1)

    out_path = OUTPUT_DIR / f"{code}.jpg"
    if out_path.exists():
        print(f"  Skip {code} (already exists)")
        return

    print(f"  Processing: {code}")
    data = load_record(code)
    if data is None:
        print(f"  SKIP {code}: không lấy được dữ liệu trang tính sau nhiều lần thử")
        return

    cw = DESIGN["canvas"]["w"]
    ch = DESIGN["canvas"]["h"]
    canvas = Image.new("RGBA", (cw, ch), (20, 20, 30, 255))

    for el in DESIGN.get("elements", []):
        try:
            render_element(canvas, el, code, data)
        except Exception as e:
            print(f"  [WARN] Element {el.get('type')}: {e}")

    save_jpeg(canvas, out_path)
    size_kb = out_path.stat().st_size // 1024 if out_path.exists() else 0
    print(f"  Saved: {out_path.name} ({size_kb} KB)")


if __name__ == "__main__":
    main()
