#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# THUMB_AR6-T1.py
# Generated by VE3 Thumb Designer - 2026-03-05 15:02
# Edit DESIGN config to customize layout and colors.
# Run: python THUMB_AR6-T1.py <code>

import sys, io, re, unicodedata, json
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageOps, ImageFilter
import gspread
from google.oauth2.service_account import Credentials

BASE_DIR    = Path(__file__).parent
VISUAL_DIR  = Path("D:/AUTO/VISUAL")
OUTPUT_DIR  = BASE_DIR / "thumbnails"
FONTS_DIR   = BASE_DIR.parent / "fonts"
CONFIG_FILE = BASE_DIR.parent / "config" / "config.json"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ===========================================================================
# DESIGN CONFIG (generated by Thumb Designer - edit to customize)
# ===========================================================================
DESIGN = {
    "canvas": {
        "w": 1920,
        "h": 1080
    },
    "elements": [
        {
            "id": 1,
            "type": "background",
            "x": 0,
            "y": 0,
            "w": 1920,
            "h": 1080,
            "color": "#005d9e",
            "image_path": "assets/AR6-T1.jpg"
        },
        {
            "id": 2,
            "type": "text_main",
            "x": 40,
            "y": 130,
            "w": 1840,
            "h": 842,
            "sample_text": "SAMPLE TEXT FOR THUMBNAIL",
            "font": "UTM-AvoBold",
            "color": "#000000",
            "highlight_color": "#ff4000",
            "min_font": 36,
            "max_font": 388,
            "line_spacing": 10,
            "align": "center",
            "stroke_width": 0,
            "stroke_color": "#000000"
        }
    ]
}
# ===========================================================================

FONTS_MAP = {
    "UTM-AvoBold":      FONTS_DIR / "00034-UTM-AvoBold.ttf",
    "Anton":            FONTS_DIR / "Anton-Regular.ttf",
    "Bebas Neue":       FONTS_DIR / "BebasNeue-Regular.ttf",
    "Inter Bold":       FONTS_DIR / "Inter-Bold.ttf",
    "League Spartan":   FONTS_DIR / "LeagueSpartan-ExtraBold.ttf",
    "Montserrat":       FONTS_DIR / "Montserrat-VariableFont_wght.ttf",
    "Nunito":           FONTS_DIR / "Nunito-VariableFont_wght.ttf",
    "Roboto Condensed": FONTS_DIR / "RobotoCondensed-BlackItalic.ttf",
    "Zuume SemiBold":   FONTS_DIR / "Zuume SemiBold.ttf",
}


# ============ GOOGLE SHEETS ============
def load_record(code, max_retries=5):
    import time
    for attempt in range(max_retries):
        try:
            with open(CONFIG_FILE, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            cred_path = CONFIG_FILE.parent / cfg.get("CREDENTIAL_PATH", "creds.json")
            creds = Credentials.from_service_account_file(str(cred_path), scopes=[
                "https://www.googleapis.com/auth/spreadsheets.readonly",
                "https://www.googleapis.com/auth/drive.readonly",
            ])
            gc = gspread.authorize(creds)
            ws = gc.open("AYS3").worksheet("INPUT")
            rows = ws.get_all_values()[1:]
            for r in rows:
                if r and r[0].strip() == code:
                    return {
                        "text_thumb": r[20].strip() if len(r) > 20 else "",
                        "hook":       r[21].strip() if len(r) > 21 else "",
                        "highlights": r[22].strip() if len(r) > 22 else "",
                    }
            return {"text_thumb": "", "hook": "", "highlights": ""}
        except Exception as e:
            wait = 3 * (attempt + 1)
            print(f"[WARN] Sheets error (attempt {attempt+1}/{max_retries}): {e}")
            if attempt < max_retries - 1:
                print(f"  Retry in {wait}s...")
                time.sleep(wait)
    print(f"[ERROR] Sheets failed after {max_retries} attempts. Cannot proceed without data.")
    return None


# ============ HELPERS ============
def get_font(name, size):
    path = FONTS_MAP.get(name)
    if path and Path(path).exists():
        try:
            return ImageFont.truetype(str(path), int(size))
        except Exception:
            pass
    return ImageFont.load_default()


def hex_rgba(h, a=255):
    h = str(h).lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    if len(h) != 6:
        return (128, 128, 128, a)
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16), a)


def clean_text(text):
    if not isinstance(text, str):
        text = str(text)
    text = unicodedata.normalize("NFKC", text)
    return (text.strip()
            .replace("\u2019", "'").replace("\u2018", "'")
            .replace("\u201c", '"').replace("\u201d", '"')
            .replace("\u2013", "-").replace("\u2014", "-"))


def wrap_text(draw, text, font, max_w):
    words = text.split()
    lines, line = [], ""
    for w in words:
        t = f"{line} {w}".strip()
        if draw.textlength(t, font=font) <= max_w:
            line = t
        else:
            if line:
                lines.append(line)
            line = w
    if line:
        lines.append(line)
    return lines or [text]


def split_phrases(raw):
    return [p.strip() for p in str(raw).split("|") if p.strip()]


def find_highlight_spans(full_text, phrases):
    spans = []
    for ph in phrases:
        ph = ph.strip()
        if not ph:
            continue
        tokens = [re.escape(t) for t in ph.split()]
        if not tokens:
            continue
        first, last = tokens[0], tokens[-1]
        if first and first[0].isalnum():
            first = r"\b" + first
        if last and last[-1].isalnum():
            last = last + r"\b"
        mid = r"[^\w]*\s*"
        core = first if len(tokens) == 1 else mid.join([first, *tokens[1:-1], last])
        try:
            pattern = re.compile(core, re.I | re.S)
        except re.error:
            pattern = re.compile(re.escape(ph), re.I | re.S)
        for m in pattern.finditer(full_text):
            spans.append((m.start(), m.end()))
    spans.sort()
    merged = []
    for s, e in spans:
        if merged and s <= merged[-1][1]:
            merged[-1] = (merged[-1][0], max(e, merged[-1][1]))
        else:
            merged.append((s, e))
    return merged


def draw_rich_text(draw, lines, x, y, w, font, color, hi_color, spacing, align, spans,
                   stroke_w=0, stroke_c="#000000", hi_stroke_w=0, hi_stroke_c="#000000"):
    ty = y
    char_pos = 0
    for line in lines:
        lw = int(draw.textlength(line, font=font))
        if align == "center":
            lx = x + max(0, (w - lw) // 2)
        elif align == "right":
            lx = x + w - lw - 10
        else:
            lx = x + 10

        segs, cur = [], 0
        for s, e in spans:
            s2 = s - char_pos
            e2 = e - char_pos
            ls = max(s2, 0)
            le = min(e2, len(line))
            if ls >= le:
                continue
            if ls > cur:
                segs.append((line[cur:ls], False))
            segs.append((line[ls:le], True))
            cur = le
        if cur < len(line):
            segs.append((line[cur:], False))
        if not segs:
            segs = [(line, False)]

        cx = lx
        for seg, hi in segs:
            c = hex_rgba(hi_color) if hi else hex_rgba(color)
            sw = hi_stroke_w if hi else stroke_w
            sc = hex_rgba(hi_stroke_c if hi else stroke_c)
            if sw > 0:
                draw.text((cx, ty), seg, fill=c, font=font, stroke_width=sw, stroke_fill=sc)
            else:
                draw.text((cx, ty), seg, fill=c, font=font)
            cx += int(draw.textlength(seg, font=font))

        ty += font.size + spacing
        char_pos += len(line) + 1


def save_jpeg(img, path, max_bytes=2_000_000):
    rgb = img.convert("RGB")
    for _ in range(4):
        for q in range(95, 49, -5):
            buf = io.BytesIO()
            rgb.save(buf, format="JPEG", quality=q, optimize=True,
                     progressive=True, subsampling="4:2:0")
            if buf.tell() <= max_bytes:
                path.parent.mkdir(parents=True, exist_ok=True)
                with open(path, "wb") as f:
                    f.write(buf.getvalue())
                return
        new_w = int(rgb.width * 0.9)
        new_h = int(rgb.height * 0.9)
        if new_w < 640:
            break
        rgb = rgb.resize((new_w, new_h), Image.LANCZOS)
    rgb.save(path, format="JPEG", quality=50, optimize=True, progressive=True)


# ============ RENDER ELEMENTS ============
def render_element(canvas, el, code, data):
    draw = ImageDraw.Draw(canvas)
    cw, ch = canvas.size
    t = el["type"]
    x = int(el.get("x", 0))
    y = int(el.get("y", 0))
    w = int(el.get("w", cw))
    h = int(el.get("h", ch))

    if t == "background":
        img_path = el.get("image_path", "")
        if img_path:
            full = BASE_DIR / img_path if not Path(img_path).is_absolute() else Path(img_path)
            if full.exists():
                bg = Image.open(full).convert("RGBA")
                bg = ImageOps.fit(bg, (cw, ch), Image.LANCZOS)
                canvas.paste(bg, (0, 0))
                return
        canvas.paste(Image.new("RGBA", (cw, ch), hex_rgba(el.get("color", "#1a1a2e"))), (0, 0))

    elif t == "photo":
        # Try thumb_004.png first, fallback to thumb_003.png, then any image
        thumb_dir = VISUAL_DIR / code / "thumbnail"
        photo_path = thumb_dir / "thumb_004.png"
        if not photo_path.exists():
            photo_path = thumb_dir / "thumb_003.png"
        if not photo_path.exists():
            for ext in (".png", ".jpg", ".jpeg", ".webp"):
                for _f in thumb_dir.glob(f"*{ext}"):
                    photo_path = _f; break
                else: continue
                break
        if not photo_path.exists():
            print(f"  [WARN] Photo not found in: {thumb_dir}")
            return
        img = Image.open(photo_path).convert("RGBA")
        scale = h / img.height
        nw = int(img.width * scale)
        img = img.resize((nw, h), Image.LANCZOS)
        if nw > w:
            cx = (nw - w) // 2
            img = img.crop((cx, 0, cx + w, h))
        canvas.paste(img, (x, y), img)

    elif t == "text_main":
        text = clean_text(data.get("text_thumb", ""))
        if not text:
            return
        transform = el.get("text_transform", "none")
        if transform == "upper": text = text.upper()
        elif transform == "lower": text = text.lower()
        color       = el.get("color", "#ffffff")
        hi_color    = el.get("highlight_color", "#ffca22")
        font_name   = el.get("font", "UTM-AvoBold")
        min_sz      = int(el.get("min_font", 36))
        max_sz      = int(el.get("max_font", 200))
        spacing     = int(el.get("line_spacing", 10))
        align       = el.get("align", "center")
        stroke_w    = int(el.get("stroke_width", 0))
        stroke_c    = el.get("stroke_color", "#000000")
        hi_stroke_w = int(el.get("hi_stroke_width", 0))
        hi_stroke_c = el.get("hi_stroke_color", "#000000")
        phrases     = split_phrases(data.get("highlights", ""))

        for size in range(max_sz, min_sz - 1, -2):
            f = get_font(font_name, size)
            lines = wrap_text(draw, text, f, w - 20)
            total_h = len(lines) * size + max(0, len(lines) - 1) * spacing
            if total_h <= h - 20:
                ty = y + max(0, (h - total_h) // 2)
                full_txt = "\n".join(lines)
                spans = find_highlight_spans(full_txt, phrases)
                draw_rich_text(draw, lines, x, ty, w, f, color, hi_color, spacing, align, spans,
                               stroke_w, stroke_c, hi_stroke_w, hi_stroke_c)
                return
        f = get_font(font_name, min_sz)
        lines = wrap_text(draw, text, f, w - 20)
        full_txt = "\n".join(lines)
        spans = find_highlight_spans(full_txt, phrases)
        draw_rich_text(draw, lines, x, y + 10, w, f, color, hi_color, spacing, align, spans,
                       stroke_w, stroke_c, hi_stroke_w, hi_stroke_c)

    elif t == "hook":
        text = clean_text(data.get("hook", "")).upper()
        if not text:
            return
        color        = el.get("color", "#000000")
        bg_color     = el.get("bg_color", "#ffca22")
        font_name    = el.get("font", "Anton")
        shape        = el.get("shape", "pill")
        stroke_w     = int(el.get("stroke_width", 0))
        stroke_color = el.get("stroke_color", "#000000")

        bg_rgba = hex_rgba(bg_color)
        if shape == "pill" and hasattr(draw, "rounded_rectangle"):
            r = min(h // 2, 40)
            draw.rounded_rectangle([x, y, x+w, y+h], radius=r, fill=bg_rgba)
        elif shape == "rect":
            draw.rectangle([x, y, x+w, y+h], fill=bg_rgba)

        cx = x + w // 2
        cy = y + h // 2
        for sz in range(min(h - 10, 160), 20, -2):
            f = get_font(font_name, sz)
            tw = int(draw.textlength(text, font=f))
            if tw <= w - 40:
                if stroke_w > 0:
                    draw.text((cx, cy), text, fill=hex_rgba(stroke_color),
                              font=f, anchor="mm", stroke_width=stroke_w,
                              stroke_fill=hex_rgba(stroke_color))
                draw.text((cx, cy), text, fill=hex_rgba(color), font=f, anchor="mm")
                break

    elif t == "text_static":
        text = el.get("text", "")
        if not text:
            return
        color     = el.get("color", "#ffffff")
        font_name = el.get("font", "UTM-AvoBold")
        size      = int(el.get("font_size", 60))
        align     = el.get("align", "center")
        f = get_font(font_name, size)
        tw = int(draw.textlength(text, font=f))
        if align == "center":
            tx = x + max(0, (w - tw) // 2)
        elif align == "right":
            tx = x + w - tw - 10
        else:
            tx = x + 10
        ty3 = y + max(0, (h - size) // 2)
        draw.text((tx, ty3), text, fill=hex_rgba(color), font=f)


# ============ MAIN ============
def main():
    code = sys.argv[1] if len(sys.argv) > 1 else None
    if not code:
        print("Usage: python THUMB_AR6-T1.py <code>")
        sys.exit(1)

    out_path = OUTPUT_DIR / f"{code}.jpg"
    if out_path.exists():
        print(f"  Skip {code} (already exists)")
        return

    print(f"  Processing: {code}")
    data = load_record(code)
    if data is None:
        print(f"  SKIP {code}: không lấy được dữ liệu trang tính sau nhiều lần thử")
        return

    cw = DESIGN["canvas"]["w"]
    ch = DESIGN["canvas"]["h"]
    canvas = Image.new("RGBA", (cw, ch), (20, 20, 30, 255))

    for el in DESIGN.get("elements", []):
        try:
            render_element(canvas, el, code, data)
        except Exception as e:
            print(f"  [WARN] Element {el.get('type')}: {e}")

    save_jpeg(canvas, out_path)
    size_kb = out_path.stat().st_size // 1024 if out_path.exists() else 0
    print(f"  Saved: {out_path.name} ({size_kb} KB)")


if __name__ == "__main__":
    main()
